### ISSUE TITLE
Some questions about RootSignature

### ISSUE THREAD

**Issue by Zachary-Zuo** [KaiH0717/Kaguya#3]
Hi, I noticed that in the D3D12RootSignature::AddBindlessParameters function, the RegisterSpace of the different DescriptorTable is set to a number of values from 100 to 103, is there any basis for the selection of these values? Why are these values chosen? Different DescriptorTable may use the same RegisterSpace, won't there be any conflict between them?

I looked up the DX12 documentation, but there is no information about these specific values. I'm still new to DX12, is there any blogs or articles about RootSignature and D3D12DescriptorTable other than the documentation?

Thanks a lot.

**Comment by Zachary-Zuo** [comment]
I now understand that different DescriptorTable corresponds to different DescriptorHeap so there is no conflict even if they have the same RegisterSpace. But the interval between the RegisterSpace of different SRVRange is only 1, won't there be overlap when NumDescriptors is set to UINT_MAX? Is it possible to define countless Descriptors under each slot? How is the physical storage of that slot done?

**Comment by kcloudy0717** [comment]
The register space I used for bindless descriptors are arbitrarily chosen by me, Is very rare for register spaces to exceed 100 (You typically don't use register spaces at all), they are simply magic numbers. Descriptor tables does not correspond to different descriptor heap, you can only bind a single CBV_SRV_UAV and SAMPLER heap at a time and SetRootDescriptorTable call on the command list will refer to that heap. The whole idea of spaces is to remove the overlapping boundaries for descriptor tables.

There isn't a physical size known of unbound descriptor tables in the shader. The shader simply doesn't care, think of
`Texture2D		  g_Texture2DTable[] : register(t0, space101);` as
`Texture2D* g_Texture2DTable : register(t0, space101);`
The array simple decayed to a pointer with no known size in the shader. The only physical limit here is how many descriptors you have in your descriptor heap.

The one cool thing about the bindless parameter setup for root signature is that all of the descriptor range offsets for different resource types (SRV, UAV, Sampler) are 0 and since I bind the start of the descriptor heap to SetRootDescriptorTable, I'm effectively aliasing the entire descriptor heap to different resource types, let me give an example, say your descriptor heap looks like this:

Descriptor heap with 7 descriptors:
| SRV: Texture2D_0 | SRV: Texture2D_1 | UAV: RWTexture_0 | unused | SRV: Texture2D_2 | SRV: Texture2DArray_0 | UAV: RWTexture_1 |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |

What the SRV bindless descriptor tables will see is essentially this:

`Texture2D		  g_Texture2DTable[] : register(t0, space101)`:
| Texture2D_0 | Texture2D_1 | undefined | unused | Texture2D_2 | undefined | undefined |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |

`Texture2DArray	  g_Texture2DArrayTable[] : register(t0, space102);`:
| undefined | undefined | undefined | unused | undefined | Texture2DArray_0 | undefined |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |

And what UAV bindless descriptor table will see:
`RWTexture2D<float4> g_RWTexture2DTable[] : register(u0, space100);`:
| undefined | undefined | RWTexture_0 | unused | undefined | undefined | undefined |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |

Attempting to access undefined/unused will most likely cause a TDR or some other undefined behavior, so you shouldn't do that lol...

I hope this explains how bindless works underneath the hood, feel free to ask me any other questions. You can add me on discord if you have discord: Kai-_-#1726

I usually respond faster there.

**Comment by kcloudy0717** [comment]
One thing I like to note is that, I will probably end up removing bindless descriptor table and just use Shader model 6.6's `ResourceDescriptorHeap` and `SamplerDescriptorHeap` instead in the future.

**Comment by Zachary-Zuo** [comment]
Thank you very much for your answer, I have sent a friend request on discord.
